apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eval-platform.fullname" . }}-worker
  namespace: vitea-data
  labels:
    {{- include "eval-platform.workerLabels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eval-platform.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.externalSecrets.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/external-secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "eval-platform.workerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eval-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      # Init containers to wait for dependencies
      initContainers:
        - name: wait-for-db
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database is ready!"
          envFrom:
            - configMapRef:
                name: {{ include "eval-platform.fullname" . }}-config
          {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "eval-platform.fullname" . }}-secrets
          {{- end }}

        - name: wait-for-redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - |
              until redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} ping; do
                echo "Waiting for Redis..."
                sleep 2
              done
              echo "Redis is ready!"
          envFrom:
            - configMapRef:
                name: {{ include "eval-platform.fullname" . }}-config

      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "eval-platform.fullname" . }}-config
          {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "eval-platform.fullname" . }}-secrets
          {{- end }}
          env:
            # Override database URLs to include password from secret
            {{- if .Values.externalSecrets.enabled }}
            - name: APP_DATABASE_URL
              value: "postgresql://{{ .Values.env.DB_USER }}:$(dbPassword)@{{ .Values.env.DB_HOST }}:{{ .Values.env.DB_PORT }}/{{ .Values.env.DB_NAME }}"
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.env.DB_USER }}:$(dbPassword)@{{ .Values.env.DB_HOST }}:{{ .Values.env.DB_PORT }}/{{ .Values.env.DB_NAME }}"
            {{- end }}
          {{- if .Values.healthChecks.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.healthChecks.worker.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: app-cache
              mountPath: /app/.cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: app-cache
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}