# Local development values for Minikube
# Overrides base values.yaml for local development

nameOverride: "evaluator"
fullnameOverride: "evaluator"

# API Configuration for local
api:
  replicaCount: 1
  image:
    repository: evaluator-api-local
    tag: latest
    pullPolicy: Never  # Use local images

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false

  # Development command with reload
  command:
    - /app/.venv/bin/uvicorn
    - app.main:app
    - --host
    - "0.0.0.0"
    - --port
    - "8000"
    - --reload

# Worker Configuration for local
worker:
  replicaCount: 1
  image:
    repository: evaluator-worker-local
    tag: latest
    pullPolicy: Never  # Use local images

  command:
    - /app/.venv/bin/celery
    - -A
    - app.workers.celery_app
    - worker
    - --loglevel=debug
    - --concurrency=1

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: false

# Evaluator Service Configuration for local
evaluator:
  replicaCount: 1
  image:
    repository: evaluator-service-local
    tag: latest
    pullPolicy: Never  # Use local images

  service:
    type: ClusterIP
    port: 8001
    targetPort: 8001

  env:
    LOG_LEVEL: "DEBUG"

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false

# Environment Variables for local
env:
  # Application settings
  APP_ENV: integration
  APP_DEPLOYMENT_TIER: integration
  DEBUG: "true"

  # Local service discovery
  APP_EVALUATOR_SERVICE_URL: "http://eval-platform-evaluator.vitea-data.svc.cluster.local:8001"

  # Use external Redis and PostgreSQL (running on host machine)
  REDIS_URL: "redis://host.minikube.internal:6379/2"
  CELERY_BROKER_URL: "redis://host.minikube.internal:6379/3"
  CELERY_RESULT_BACKEND: "redis://host.minikube.internal:6379/4"

  # Use external PostgreSQL (running on host machine port 15432)
  DB_HOST: "host.minikube.internal"
  DB_PORT: "15432"
  DB_USER: "evaladmin"
  DB_NAME: "evaluation_db"
  APP_DATABASE_URL: "postgresql://evaladmin:postgres123@host.minikube.internal:15432/evaluation_db"
  DATABASE_URL: "postgresql+asyncpg://evaladmin:postgres123@host.minikube.internal:15432/evaluation_db"

  # OpenTelemetry endpoints (pointing to host machine)
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://host.minikube.internal:10318/v1/traces"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://host.minikube.internal:10318/v1/logs"

  # Additional guardrail services (using Docker Compose names mapped to K8s services)
  SECRETS_DETECTOR_SERVICE_URL: "http://secrets-detector.vitea-data.svc.cluster.local:8081"
  PROFANITY_GUARD_SERVICE_URL: "http://profanity-guard.vitea-data.svc.cluster.local:8082"
  JAILBREAK_GUARD_SERVICE_URL: "http://jailbreak-guard.vitea-data.svc.cluster.local:8086"

  # Debug logging for local
  LOG_LEVEL: "DEBUG"

  # Guardrail service URLs (local K8s services)
  PIIGUARD_SERVICE_URL: "http://pii-guard.vitea-data.svc.cluster.local:8080"
  POLICY_ENGINE_URL: "http://policy-engine.vitea-data.svc.cluster.local:8000"

# Security context - more permissive for local development
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false  # Allow writes for local debugging
  runAsNonRoot: true
  runAsUser: 1000

# External Secrets for local (disabled since using hardcoded values for dev)
externalSecrets:
  enabled: false
  secretStore: azure-keyvault-local
  refreshInterval: 30s
  secrets:
    dbPassword: "eval-platform-db-password"
    redisPassword: "redis-password"
    appSecretKey: "eval-platform-secret-key"
    # openaiApiKey: "openai-api-key"  # uncomment if needed
    # azureOpenaiApiKey: "azure-openai-api-key"  # uncomment if needed

# Database migration for local
migration:
  enabled: true
  image:
    repository: evaluator-api-local
    tag: latest
    pullPolicy: Never

# Pod disruption budget - disabled for local
podDisruptionBudget:
  enabled: false